server.:
  port: 5000
  servlet:
    context-path: /test
backenddevtest:
  rest:
    client:
      product:
        base-url: http://localhost:3001
        connection-timeout: 5000
        read-timeout: 5000
local:
  server:
    port: 8080